# Generated by Django 5.2.10 on 2026-03-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0002_commande_lignecommande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='mode_paiement',
            field=models.CharField(choices=[('livraison', 'Paiement à la livraison'), ('momo', 'MTN Mobile Money'), ('orange', 'Orange Money')], default='livraison', max_length=20),
        ),
        migrations.AddField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('attente', 'En attente'), ('paye', 'Payée'), ('livree', 'Livrée')], default='attente', max_length=20),
        ),
    ]
